# Generated by Django 5.1.1 on 2024-09-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('check_in_dates', models.DateField()),
                ('check_out_dates', models.DateField()),
                ('room_number', models.IntegerField(max_length=3)),
                ('type_of_room', models.CharField(max_length=10)),
                ('package_included', models.BooleanField()),
            ],
        ),
    ]
